// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApp;

#nullable disable

namespace SimpleApp.Migrations
{
    [DbContext(typeof(SimpleAppContext))]
    [Migration("20220330114901_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("SimpleApp.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("ProtocolId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SimpleApp.Protocol", b =>
                {
                    b.Property<int>("ProtocolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmmNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasuredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkpieceName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProtocolId");

                    b.ToTable("Protocols");

                    b.HasData(
                        new
                        {
                            ProtocolId = 1,
                            CmmNumber = "112233",
                            DrawingNumber = "11",
                            FileName = "28022022114012_IV05N002R0.pdf",
                            MeasuredOn = new DateTime(2022, 3, 30, 13, 49, 1, 569, DateTimeKind.Local).AddTicks(497),
                            Name = "mein_block_testv1",
                            OperatorName = "",
                            OrderNumber = "",
                            PartNumber = "11",
                            SoftwareVersion = "",
                            WorkpieceName = ""
                        },
                        new
                        {
                            ProtocolId = 2,
                            CmmNumber = "112233",
                            DrawingNumber = "8",
                            FileName = "24022022112318_IV05N002R0.pdf",
                            MeasuredOn = new DateTime(2022, 3, 30, 13, 49, 1, 569, DateTimeKind.Local).AddTicks(540),
                            Name = "mein_block_testv2",
                            OperatorName = "",
                            OrderNumber = "",
                            PartNumber = "8",
                            SoftwareVersion = "",
                            WorkpieceName = ""
                        },
                        new
                        {
                            ProtocolId = 3,
                            CmmNumber = "112233",
                            DrawingNumber = "9",
                            FileName = "24022022112244_IV05N002R0.pdf",
                            MeasuredOn = new DateTime(2022, 3, 30, 13, 49, 1, 569, DateTimeKind.Local).AddTicks(542),
                            Name = "mein_block_testv3",
                            OperatorName = "",
                            OrderNumber = "",
                            PartNumber = "9",
                            SoftwareVersion = "",
                            WorkpieceName = ""
                        },
                        new
                        {
                            ProtocolId = 4,
                            CmmNumber = "112233",
                            DrawingNumber = "11",
                            FileName = "24022022112301_IV05N002R0.pdf",
                            MeasuredOn = new DateTime(2022, 3, 30, 13, 49, 1, 569, DateTimeKind.Local).AddTicks(545),
                            Name = "mein_block_testv4",
                            OperatorName = "",
                            OrderNumber = "",
                            PartNumber = "11",
                            SoftwareVersion = "",
                            WorkpieceName = ""
                        },
                        new
                        {
                            ProtocolId = 5,
                            CmmNumber = "112233",
                            DrawingNumber = "11",
                            FileName = "20122021070353_IV05N002R0.pdf",
                            MeasuredOn = new DateTime(2022, 3, 30, 13, 49, 1, 569, DateTimeKind.Local).AddTicks(547),
                            Name = "mein_block_testv5",
                            OperatorName = "",
                            OrderNumber = "",
                            PartNumber = "11",
                            SoftwareVersion = "",
                            WorkpieceName = ""
                        });
                });

            modelBuilder.Entity("SimpleApp.Comment", b =>
                {
                    b.HasOne("SimpleApp.Protocol", "Protocol")
                        .WithMany("Comments")
                        .HasForeignKey("ProtocolId");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SimpleApp.Protocol", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
