// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApp;

#nullable disable

namespace SimpleApp.Migrations
{
    [DbContext(typeof(SimpleAppContext))]
    [Migration("20220329094051_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("SimpleApp.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProtocolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("ProtocolId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SimpleApp.Protocol", b =>
                {
                    b.Property<int>("ProtocolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmmNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CncName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawingNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasuredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined1")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined2")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined3")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined4")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined5")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined6")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDefined7")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkpieceName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProtocolId");

                    b.ToTable("Protocols");

                    b.HasData(
                        new
                        {
                            ProtocolId = 1,
                            DrawingNumber = "Test",
                            MeasuredOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "First Protocol"
                        });
                });

            modelBuilder.Entity("SimpleApp.Comment", b =>
                {
                    b.HasOne("SimpleApp.Protocol", "Protocol")
                        .WithMany("Comments")
                        .HasForeignKey("ProtocolId");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SimpleApp.Protocol", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
